
version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    
    environment:
      - DEBUG=${DEBUG-}     # show all logs
      - DOCKER_HOST=unix:///var/run/docker.sock
      #- SERVICES=s3, iam, lambda, dynamodb, cloudwatch     #specify the service
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - AWS_DEFAULT_REGION=us-east-1
    
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack_data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


# testing: 
# http://localhost:4566/health
# http://localhost:4566/_localstack/health
# http://localhost:4566/_localstack/info

